### ISSUE TITLE
GeoLayout exception

### ISSUE THREAD

**Issue by sheymann** [jacomyal/GeoLayout#4]
It happens when latitude and longitude columns are FLOAT type instead of DOUBLE:

java.lang.ClassCastException: java.lang.Float cannot be cast to org.gephi.data.attributes.type.DynamicDouble
    at org.gephi.plugins.layout.geo.GeoLayout.goAlgo(GeoLayout.java:137)
    at org.gephi.layout.LayoutControllerImpl$LayoutRun.run(LayoutControllerImpl.java:178)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:251)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)

The plugin author may handle this situation because the required column type it is not written in the documentation.

**Comment by sheymann** [comment]
Commit by Mathieu Bastian on https://github.com/gephi/gephi-plugins/commits/geolayout
